

service: Bert-lambda-before

provider:
  name: aws # provider
  # region: eu-central-1 # aws region
  memorySize: 5120 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6

functions:
  questionanswering:
    handler: handler.handler
    events:
      - http:
          path: qa # http path
          method: post # http method