
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-08T13:27:20-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "41e1657948b18008d302f5cb8af06539adc7c792",
 "version": "11.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
